// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXGJFgLvzA27KOFRN6uRxpcXKS0_H44zI',
    appId: '1:447574493724:web:c8f8237ffdc96f290cedd9',
    messagingSenderId: '447574493724',
    projectId: 'student-task-dea95',
    authDomain: 'student-task-dea95.firebaseapp.com',
    storageBucket: 'student-task-dea95.firebasestorage.app',
    measurementId: 'G-GHD8PB9YKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwbQ8gE2y4_EDO3FYSlBSkLeNdLPo9BMI',
    appId: '1:447574493724:android:c9ef6d1089a3698d0cedd9',
    messagingSenderId: '447574493724',
    projectId: 'student-task-dea95',
    storageBucket: 'student-task-dea95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz7m2ti9c329LLqX06T1mTUyENU3TzqQA',
    appId: '1:447574493724:ios:76092e835b078bd50cedd9',
    messagingSenderId: '447574493724',
    projectId: 'student-task-dea95',
    storageBucket: 'student-task-dea95.firebasestorage.app',
    iosBundleId: 'com.example.studentTaskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz7m2ti9c329LLqX06T1mTUyENU3TzqQA',
    appId: '1:447574493724:ios:76092e835b078bd50cedd9',
    messagingSenderId: '447574493724',
    projectId: 'student-task-dea95',
    storageBucket: 'student-task-dea95.firebasestorage.app',
    iosBundleId: 'com.example.studentTaskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXGJFgLvzA27KOFRN6uRxpcXKS0_H44zI',
    appId: '1:447574493724:web:9559157c8c719e7d0cedd9',
    messagingSenderId: '447574493724',
    projectId: 'student-task-dea95',
    authDomain: 'student-task-dea95.firebaseapp.com',
    storageBucket: 'student-task-dea95.firebasestorage.app',
    measurementId: 'G-K9Y3Y7TMEZ',
  );
}
